---

elasticsearch:
  index: 'elastic_cron-%{+YYYY.MM.dd}'
  servers:
    - http://localhost:9200
  auth: [username, password]

jobs:
  - name: date
    schedule: "0 * * * * *"
    cmd: "/bin/date"
    args:
      - "+%+"

...
